name: Sync to GitLab

on:
  push:
    branches: [main]

jobs:
  git-sync-gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          # 注意在 Settings->Secrets 配置 GITLAB_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:douba0/doubao.git
          # 注意替换为你的 gitlab 目标仓库地址
          destination-repo: git@gitlab.com:douba0/doubao.git

